[package]
name = "tonapi-rs"
version = "0.0.1"
edition = "2021"
license = "MIT"
authors = ["S. Suprun <hello@syoma.website>"]

[dependencies]
async-trait = { version = "0.1.83" }
reqwest = { version = "0.12.9" }
